config/routes.rb
PFerreiraIndproj::Application.routes.draw {

  resources :technicians

  resources :customers

  resources :tickets do
    resources :actions
  end

}

app/models/technician.rb
class Technician < ActiveRecord::Base
  attr_accessible :name
  #require data in fields
  validates_presence_of :name
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  # GET /technicians
  # GET /technicians.json
  def index
    @technicians = Technician.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @technicians }
    end
  end

  # GET /technicians/1
  # GET /technicians/1.json
  def show
    @technician = Technician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @technician }
    end
  end

  # GET /technicians/new
  # GET /technicians/new.json
  def new
    @technician = Technician.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @technician }
    end
  end

  # GET /technicians/1/edit
  def edit
    @technician = Technician.find(params[:id])
  end

  # POST /technicians
  # POST /technicians.json
  def create
    @technician = Technician.new(params[:technician])

    respond_to do |format|
      if @technician.save
        format.html { redirect_to @technician, notice: 'Technician was successfully created.' }
        format.json { render json: @technician, status: :created, location: @technician }
      else
        format.html { render action: "new" }
        format.json { render json: @technician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /technicians/1
  # PUT /technicians/1.json
  def update
    @technician = Technician.find(params[:id])

    respond_to do |format|
      if @technician.update_attributes(params[:technician])
        format.html { redirect_to @technician, notice: 'Technician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @technician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technicians/1
  # DELETE /technicians/1.json
  def destroy
    @technician = Technician.find(params[:id])
    @technician.destroy

    respond_to do |format|
      format.html { redirect_to technicians_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/technicians/_form.html.erb
<%= form_for(@technician) do |f| %>
  <% if @technician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technician.errors.count, "error") %> prohibited this technician from being saved:</h2>

      <ul>
      <% @technician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technicians/edit.html.erb
<h1>Editing technician</h1>

<%= render 'form' %>

<%= link_to 'Show', @technician %> |
<%= link_to 'Back', technicians_path %>

app/views/technicians/index.html.erb
<h1>Listing technicians</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @technicians.each do |technician| %>
  <tr>
    <td><%= technician.name %></td>
    <td><%= link_to 'Show', technician %></td>
    <td><%= link_to 'Edit', edit_technician_path(technician) %></td>
    <td><%= link_to 'Destroy', technician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Technician', new_technician_path %>

app/views/technicians/new.html.erb
<h1>New technician</h1>

<%= render 'form' %>

<%= link_to 'Back', technicians_path %>

app/views/technicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @technician.name %>
</p>


<%= link_to 'Edit', edit_technician_path(@technician) %> |
<%= link_to 'Back', technicians_path %>