config/routes.rb
PFerreiraIndproj::Application.routes.draw {

  resources :technicians

  resources :customers

  resources :tickets do
    resources :actions
  end

}

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :customer_id, :problem
  belongs_to :customer
  has_many :actions

  #require data in fields
  validates_presence_of :problem, :customer_id

  # @return [Search]
  def self.search search_term
     return scoped unless search_term.present?
     where(['customers: ', "%#{search_term}%"])
   end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
    @tickets = Ticket.search(params[:search])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @tickets = Ticket.search(params[:search]).all
    flash[:ticket_id] = @tickets

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
  #add action
  def ticket_action
    @act = Action.new(
        'ticket_id' => flash[:ticket_id],
        'description' => flash[:description]['description'],
        'technician_id' => flash[:actTechnician]['technician_id']
    )
    id @act.save
    flash[:notice]  = 'Action was successfully added'
    redirect_to :action => 'show', :id => flash[:ticket_id ]

  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :customer_id %><br />
    <%= select('ticket','customer_id', Customer.all.collect{|c| [c.name, c.id]}) %>
  </div>
  <div class="field">
    <%= f.label :problem %><br />
    <%= f.text_field :problem %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<%= form_tag tickets_path, :method => :get do %>
    <p>
      <b>search by customer ID #:</b>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag 'search', :customer_id => nil %>
    </p>
<% end %>

<table>
  <th>Ticket #</th>
  <th>Summary</th>
  <th>Customer</th>
  <th>Created</th>
  <th>Updated</th>



  <th></th>
  <th></th>
  <th></th>
  </tr>

  <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.problem %></td>
        <td><%= ticket.customer.name %></td>
        <td><%= ticket.created_at %></td>
        <td><%= ticket.updated_at%></td>

        <td><%=  %></td>

        <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p>
  <b>Customer:</b>
  <%= @ticket.customer_id %>
</p>

<p>
  <b>Problem:</b>
  <%= @ticket.problem %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

<hr>
<h2>Actions</h2>
<table>
  <tr>
    <th>Customer</th>
    <th>Description</th>
  </tr>
  <% for action in @ticket.actions %>
      <tr>
        <td><%= action.call_id %></td>
        <td><%= action.description %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Action', new_ticket_action_path(@ticket) %>
<%= link_to 'All Actions', ticket_action_path(@ticket) %>